### ISSUE TITLE
AWS setup - provision EC2 instance

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/minidream-r-env#10]
Start a Linux EC2 instance (e.g. via PR provisioning system at Sage). 
This needs to be a large instance, at least

r4.16xlarge - https://aws.amazon.com/blogs/aws/new-next-generation-r4-memory-optimized-ec2-instances/

In the past [that](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/154/files)^ has worked, however 2021 would have more students (~25). I'd opt for instance with even more memory and CPUs. Let's discuss @BrunoGrandePhD.

Note: the instance needs to be publicly accessible. (E.g. on a public subnet; load balancer is fine - whichever solution works as long as users have access via web; port 8787). There will be only public-access data stored on the vm.

**Comment by BrunoGrandePhD** [comment]
I'm opened the [PR](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/478) to deploy the EC2 instance and the ALB. A key difference from the 2020 resources is the larger instance type. I opted for `x1.16xlarge`, which features 64 vCPUs, 976 GiB of memory, and a local 1920-GiB SSH drive. The [estimated cost](https://calculator.aws/#/estimate?id=f8ac0f4d05e577144a08ae8fd4d2f8517f57b398) is $4918/month, which is 55% more than the [estimated cost](https://calculator.aws/#/estimate?id=f8ac0f4d05e577144a08ae8fd4d2f8517f57b398) for last year.

**Comment by BrunoGrandePhD** [comment]
The EC2 instance (`10.5.17.96`) is up and running. The ALB (`minid-LoadB-2NGAPNUGRA9L-1218544098.us-east-1.elb.amazonaws.com`) is also up, but I need Khai to update the `minidream.synapse.org` subdomain first for HTTPS to work. I'm going to set up the load balancer on the EC2 instance to redirect HTTPS traffic to 8787 to confirm that the ALB+EC2 setup works.

**Comment by BrunoGrandePhD** [comment]
Done! https://minidream.synapse.org/
