### ISSUE TITLE
AWS setup - deploy RStudio environment container

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/minidream-r-env#11]
See documentation here [here](https://github.com/milen-sage/minidream-r-env#aws-instance-setup--dependencies). 

Note: 
- I wrote those a while back and in a hurry, hopefully are fairly complete and consistent but can't have both :) please use common sense. Also, if you notice setup deficiencies (and I am aware of at least a couple) please note and/or resolve.
- setting this up allows challenge solution submission to Synapse, through the RStudio environment; the setup has some subtleties - I'd plan on about 4-6 hours of work here (but hopefully the instructions speed that up).

**Comment by BrunoGrandePhD** [comment]
**Note to Self:** The infrastructure deployed in Sage-Bionetworks/scicomp-provisioner#478 requires an nginx reverse proxy to redirect HTTPS traffic (port 443) to RStudio (port 8787). I'll set one up manually along with the other commands.

**Comment by BrunoGrandePhD** [comment]
**Note to Self:** Update Dockerfile to use `rocker/tidyverse:4.0.5`, which builds on top of `rocker/rstudio` (_i.e._ it includes RStudio). This should speed up image building significantly since all of the tidyverse packages (and their OS-level dependencies) are pre-installed.

**Comment by BrunoGrandePhD** [comment]
I can close this now that I completed all of the tests in #12.
