### ISSUE TITLE
Determine whether/how to use Jupyter Notebooks instead of RStudio

### ISSUE THREAD

**Issue by lopierra** [Sage-Bionetworks/minidream-r-env#21]
From Milen's email:

> It'd be great to have Jupyter notebooks in mini-DREAM, however depending on how we'd approach it, it may require a rework of at least two parts of existing infrastructure:
> - how students login in their own notebooks
> - how submissions to Synapse challenges work
> 
> Currently we are using RStudio's authentication and we have a submission interface that assumes certain R functions store yaml files containing answers. The latter should be relatively straightforward to do w/in Jupyter notebooks. But we'd have to see how authentication could work. Unless you or Bruno are aware already of a solution, we may need to do some googling on best practices for auth in Jupyter. If we are re-working authentication we might as well check if we can use an OAuth layer, so that students can use their Synapse account to use the notebooks; this is something we've wanted to do for 4 years and never got around to.

**Comment by BrunoGrandePhD** [comment]
It looks like [JupyterHub](https://jupyter.org/hub) might be what we're looking for. They claim to be:

> A multi-user version of the notebook designed for companies, classrooms and research labs

Based on a quick skim of their [OAuth documentation](https://jupyterhub.readthedocs.io/en/stable/reference/oauth.html), it might be possible to use the OAuth access token given by Synapse when the user logs in (assuming Synapse is configured as the OAuth provider). You seem to be able to configure [post-auth hooks](https://jupyterhub.readthedocs.io/en/stable/api/auth.html#jupyterhub.auth.Authenticator.run_post_auth_hook), which we could use to remember the Synapse credentials.

It might be a non-trivial amount of work to get this working, but it could be something that we could reuse across multiple hackathons/workshops.

**Comment by lopierra** [comment]
On the other hand, if students are learning R, shouldn't they also learn to use RStudio? 🤷‍♀️

**Comment by lopierra** [comment]
Per email with Diana, we will stick with the status quo this year and look into Jupyter (and tidyverse) for next summer. Plan to start earlier next time?
