### ISSUE TITLE
AWS setup - provision EC2 instance

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/minidream-r-env#22]
Distilled from https://github.com/Sage-Bionetworks/minidream-r-env/issues/10

**Describe the solution you'd like**

- [ ] Start a Linux EC2 instance (e.g. via PR provisioning system at Sage). This needs to be a large instance -- the 2021 cohort (~25 students) used a x1.16xlarge, which features 64 vCPUs, 976 GiB of memory, and a local 1920-GiB SSH drive. 

**Note**: the instance needs to be publicly accessible. (E.g. on a public subnet; load balancer is fine - whichever solution works as long as users have access via web; port 8787). There will be only public-access data stored on the vm.

From @BrunoGrandePhD in 2021 for additional context: 

> I'm opened the https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/478 to deploy the EC2 instance and the ALB. A key difference from the 2020 resources is the larger instance type. I opted for x1.16xlarge, which features 64 vCPUs, 976 GiB of memory, and a local 1920-GiB SSH drive. 
> 
> The EC2 instance (10.5.17.96) is up and running. The ALB (minid-LoadB-2NGAPNUGRA9L-1218544098.us-east-1.elb.amazonaws.com) is also up, but I need Khai to update the minidream.synapse.org subdomain first for HTTPS to work. I'm going to set up the load balancer on the EC2 instance to redirect HTTPS traffic to 8787 to confirm that the ALB+EC2 setup works.

**Comment by BrunoGrandePhD** [comment]
@linglp: I'm available to help if you run into any snags! 

For this ticket, the easiest thing to do is undo this [pull request](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/504/files), which deleted the miniDREAM server from last year. You'll need to update the file names to `2022`. 

You should fork the scicomp-provisioner repo first, makes the changes on a branch in your fork, and open a PR on the upstream scicomp-provisioner repo. Feel free to open it as a draft PR and send me a link so I can review it before marking it as ready for Sage IT to review.

**Comment by linglp** [comment]
General steps: 
- The first step is to create a forked repo of [scicomp-provisioner](https://github.com/Sage-Bionetworks/scicomp-provisioner), and then copy and paste the two yaml files from the PR [here](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/504/files)
> The PR that I created for year 2022 could be found [here](https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/522)
> The general workflow goes like this: whenever we update the `aws-infra` repo, part of the CI/CD pipeline is triggered, and then it deploys the templates to a public S3 bucket. 

- Begin to edit `minidream-rstudio-2022-ec2.yaml` and `minidream-rstudio-2022-ec2-alb.yaml`:
> These two yaml files: `minidream-rstudio-2022-ec2-alb.yaml` and `minidream-rstudio-2022-ec2.yaml` are sceptre config files. The `alb.yaml` is for configuring a load balancer, while `ec2.yaml` is for configuring an EC2 instance. Usually, load balancer is for managing traffic and maintaining balance betwen different servers. For our case, since our EC2 instance is private and can only be accessed using Sage's VPN, we need a load balancer that serves as a public entry point for students. 

For editing `minidream-rstudio-2022-ec2.yaml`
- [ ] Update `OwnerEmail`, `Project`, `Department` parameters as needed. Put them under `stack-tags` key as shown [here](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/main/config/projects-prod/ntap-add5-project.yaml#L19-L23) (*Note* :`CostCenter` parameter is for finance team. Every grant has an identifier, and IT could use this to assign costs of compute to a specific grant. )
- [ ] Check AMI ID and make sure we are using the latest version of `packer-base-ubuntu-bionic-v1.0.9`. You could check out a list of AMI IDs [here](https://ami.sageit.org/). AMI are Amazon virtual machine images, they are snapshot of what's on the hard drive, including operating systems. We are using `packer-base-ubuntu-bionic-v1.0.9`, and we need to make sure that we are using the latest version if there's a more recent version. 
- [ ] Update `template > url` and replace it with the correct version tag and file path. For example, for 2021 the version of latest `aws-infra` is `v0.2.13` while for 2022, the version is `v0.4.0` (view `jc-ec2-linux.j2` [here](https://github.com/Sage-Bionetworks/aws-infra/blob/v0.4.0/templates/EC2/jc-ec2-linux.j2))
- [ ] Ensure that `minidream-rstudio-2022-ec2.yaml` has all JC related keys from `jc-ec2-linux.j2`. If there's an new key (for example, we found out that `JcUserId` is a new key that gets added in 2022), please add it to your yaml file.  
- [ ] It might also be worthwhile to go to a list of changes that IT made (view commit history [here](https://github.com/Sage-Bionetworks/aws-infra/commits/master/templates/EC2/jc-ec2-linux.j2)) to figure out what other changes they have made. In the end, we want to ensure that all the parameters from `jc-ec2-linux.j2` are present in our `minidream-rstudio-2022-ec2.yaml` file. 
- [ ] In general, ensure that you change the file name from `2022` to a different year
- [ ] Ensure that you have the correct instance type (which depends on student size) 

For editing `minidream-rstudio-2022-ec2-alb.yaml`:
- [ ] Update the version tag and template url as above
- [ ] Update `Ec2InstanceId` and ensure that you point to the correct year. 
>Here `Ec2InstanceId` is matching we have in `minidream-rstudio-2022-ec2.yaml`
>The `dependencies` key is here is also because we referenced the Ec2 instance in `Ec2InstanceId`. Sceptre helps us keep track of all the dependencies and ensure that things are deployed in the right order. 

> All the templates (aka: `managed-ec2-linux-v2.j2` and `managed-alb-https-v2.yaml`) referenced in these two yaml files could be found from [aws-infra](https://github.com/Sage-Bionetworks/aws-infra/tree/master/templates) repository (*Note*: If you can't find your templates, please check if you are looking at the correct version of `aws-infra` repo. For 2021, based on file paths specified for `before_launch` key, we know that the version tag is `v0.2.13`). 

Historical context and other explanation: 
> Historical context: in 2021 PR [here](https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/5f0a9293e4af2c64fd96ba4f396b7fd67b47f583/config/prod/minidream-rstudio-2021-ec2.yaml#:~:text=hooks%3A,stack_group_config.aws_account_email%7D%7D%22),  you could see that we have the `before_launch` key, which is for downloading the templates to a directory called `remote`. After download, the `template_path` becomes valid (and that's why we could see `remote` directory referenced [there](https://github.com/Sage-Bionetworks/scicomp-provisioner/blob/5f0a9293e4af2c64fd96ba4f396b7fd67b47f583/config/prod/minidream-rstudio-2021-ec2.yaml#:~:text=ec2%2Dv2.yaml-,template_path%3A,-%22remote/managed). **But IT has figured out a modern way of doing it.** Please see an example [here](https://github.com/Sage-Bionetworks-Workflows/nextflow-infra/blob/main/config/infra-prod/nextflow-vpc.yaml#:~:text=template%3A,private.yaml%22) for handling template path. 

> sceptre resolver: whenever you see a `!`, that's a resolver. It is for dynamically updating values. They are handy for avoiding hard-coded values that gets deployed from other stack. For example, `!stack_output_external` in `minidream-rstudio-2022-ec2-alb.yaml` is for fetching the `Ec2InstanceId` from our Ec2 instance and replace it here. (See the definition [here)](https://docs.sceptre-project.org/dev/docs/resolvers.html#stack-output-external). Otherwise, you will have to deploy the Ec2 instance first, and then add it for `Ec2InstanceId` key

**Comment by tschaffter** [comment]
Have you consider instantiating a smaller instance for each team. This approach may be cheaper - better tailored EC2 and ability to terminate unused instances - and reduce the waste of compute resources such as unused CPU cores. @BrunoGrandePhD

**Comment by milen-sage** [comment]
@tschaffter for mini-DREAM we don't know in advance, up until halfway through the program, how many teams would need an individual  instance; and how many people on each team there are. This would pose a challenge with a multi-instance solution, even though I agree it'd be more efficient in terms of CPU resources in principle. 

To enable multi-instance solution, in the mini-DREAM case, we'd have to be much more flexible and/or elastic in terms of instance management. E.g. each student gets their own instance; over time as teams are established each team gets their own instance. This may create a few issues given the current provisioning system. We can implement that a different year when we are prepared to experiment. This mini-DREAM course starts on June 7 and we don't have much time for experimentation.

**Comment by linglp** [comment]
For connecting an EC2 instance using the command line, please check documentation [here](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/405864455/Jumpcloud)

**Comment by linglp** [comment]
@ychae Yes.
