### ISSUE TITLE
AWS setup - deploy RStudio environment container

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/minidream-r-env#23]
Distilled from #11 

**Documentation for how to do this can be found [here](https://github.com/milen-sage/minidream-r-env#aws-instance-setup--dependencies).**

**Describe the solution you'd like**

- [x] Deploy an RStudio environment container. This will allow a challenge solution submission to Synapse through the RStudio environment. The setup has some subtleties - @milen-sage estimates about _4-6 hours_ of work here (but hopefully the instructions speed that up).

From @BrunoGrandePhD:

> The infrastructure deployed in https://github.com/Sage-Bionetworks/scicomp-provisioner/pull/478 requires an `nginx` reverse proxy to redirect HTTPS traffic (port 443) to RStudio (port 8787). 
> 
> Update Dockerfile to use `rocker/tidyverse:4.0.5`, which builds on top of `rocker/rstudio` (i.e. it includes RStudio). This should speed up image building significantly since all of the tidyverse packages (and their OS-level dependencies) are pre-installed.

**Comment by BrunoGrandePhD** [comment]
@linglp: I'll be monitoring this ticket as well in case you need any help!

**Comment by ychae** [comment]
ec2 instance has been set up and shared; adding students and testing remains

**Comment by linglp** [comment]
The following users have been added as admin: 
```
Adding user thomasyu888 to groups rstudio-user,rstudio-admin
Adding user linglp to groups rstudio-user,rstudio-admin
Adding user jaeddy to groups rstudio-user,rstudio-admin
Adding user bgrande to groups rstudio-user,rstudio-admin
Adding user milen to groups rstudio-user,rstudio-admin
Adding user lopierra to groups rstudio-user,rstudio-admin

```

**Comment by ychae** [comment]
hi @linglp -- I see that this is marked Done on the project board, can this ticket be closed?

**Comment by linglp** [comment]
@ychae Yes. Thank you
