### ISSUE TITLE
Clean Synapse submission folders 

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/minidream-r-env#5]
Remove previous course content [here]( https://www.synapse.org/#!Synapse:syn25653271).

**Comment by lopierra** [comment]
@milen-sage should I delete everything in all of the folders besides Submissions? (Activities, Data, Presentations, etc.)

And is there a way to delete everything in a folder, either on the website or using {synapser}? Or would it be easier to just delete all the folders, and then re-create the empty folder structure from scratch?

**Comment by lopierra** [comment]
Steps to delete files in bulk:

1. Make a File View on Synapse that is scoped to the Submissions folder
2. Download the File View using `list_of_files_to_delete <- read_csv(synTableQuery(sprintf("SELECT * FROM syn25828643", "syn25828643"))$filepath)`
3. Delete the files using `purrr::walk(list_of_files_to_delete$id, synDelete)`

**Comment by milen-sage** [comment]
@BrunoGrandePhD when updating the submission folders on the docker-side here are the module submission folders for this year:
https://www.synapse.org/#!Synapse:syn25653271

**Comment by BrunoGrandePhD** [comment]
I noticed that the `submission_helpers.R` [script](https://github.com/BrunoGrandePhD/minidream-challenge/blob/bgrande/minidream-2021/R/submission_helpers.R#L162-L168) doesn't reference module 6. Is this expected? I'm going to update the Synapse IDs for modules 0–5 and 7 for now.
