### ISSUE TITLE
Update Synapse wikis

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/minidream-r-env#9]
Generally bring miniDREAM content on Synapse up-to-date, including

- [x] miniDREAM schedule
- [x] RStudio environment address
- [x] leaderboard scoreboards
- [x] organizers info
- [x] zoom call info
- [x] office hours info
- [x] resources lists

**Comment by lopierra** [comment]
Schedule - need descriptions for jouRney in R and Small Group Activities
